- index.html
This PR is to add Open Graph meta tags to control how open-metadata URLs are displayed when shared on social media.
> Adding Open graph meta tags

- css/styles.css
- index.html
This PR Closes #6 and also fixed button styling for the mobile screen.
> Closes #6 Update blogs list with new blog.

- index.html
> Change Feature Strip Content

- index.html
> Change version from 0.10 to 0.10.1

- community.html
- index.html
- robots.txt
- sitemap.xml
This PR will fix the following SEO issues
> Fix site seo issues - part1

- community.html
- index.html
This PR will fix the following SEO issues
> Fix site seo issues - part2

- index.html
This PR will fix Social Media Engagement - Off-page SEO issue and Schema missing issue.
> Fix seo issues part-3

- community.html
- index.html
Adding Piwik tracking code to OM Site
> Added piwik tracking code to OM site

- community.html
- index.html
- js/piwik.js
As part of this https://github.com/open-metadata/openmetadata-site/pull/45 PR we have added Piwik tracking, So this PR is for removing duplication and creating a single script file for Piwik code and linking them to both HTML files.
cc : @TeddyCr
> Add script file for piwik

- index.html
> Change cloud section content 

- community.html
I worked on moving the webinar section above the meetings section.
> Move the Webinar section above the Meetings

- css/styles.css
- index.html
remove https://share.hsforms.com/1fstvMCeZRZKTYA4nG1VTPgcq0j9 to point to https://cloud.getcollate.io
> Update landing page with link to cloud sign up page

- community.html
I worked on Updating the community page with the latest webinar and community meeting video.
> Update community page with latest webinar and community meeting video

- README.md
Update README.md with netlify deployment status badge
> Update README.md with netlify status

- index.html
I worked on changing `cloud.getcollate.io` to `getcollate.io`
> Update saas link to getcollate.io

- index.html
> chore : update site with 0.13.1 data

- index.html
Using Javascript to auto-update the footer copyright year instead of hard coding the year.
> Change footer copyright year

- css/styles.css
- js/testimonials.js
- js/testimonials.json
> chore: update testimonials details

- index.html
> chore: update release version to 1.0.0

- community.html
> update community page content

- js/testimonials.json
> Change reviewer name in bucketplace

- index.html
> chore: update 1.0.0 to 1.0

- js/testimonials.json
> chore: add loggi testimonial

- js/testimonials.json
> chore: update loggi testimonial

- src/components/Blogs/Blogs.component.tsx
- src/components/CopyCode/CopyCode.component.tsx
- src/components/Footer/Footer.component.tsx
- src/components/Integrations/Integrations.tsx
- src/components/Navbar/Navbar.component.tsx
- src/components/SaaSTrial/SaasTrial.component.tsx
- src/components/TeamsSection/TeamsSection.tsx
- src/components/TeamsSection/Testimonials.tsx
- src/components/common/BlogCard.tsx
- src/pages/community.tsx
- src/pages/index.tsx
Replaced `<a>` with `<Link>` component from next for better performance
> replace 'a' tag with Link component

- src/components/AboutOpenMetadata/AboutOpenMetadata.tsx
- src/components/Achievement/Achievement.tsx
- src/components/FooterDev/FooterDev.tsx
- src/components/IntegrationsDev/IntegrationsDev.tsx
- src/components/NavbarDev/NavbarStrip.component.tsx
- src/components/TryOpenMetadata/TryOpenMetadata.tsx
- src/styles/styles.css
- tailwind.config.js
Updated the shadows and alignments as per the feedbacks.
> Update as per feedbacks

- src/components/AboutOpenMetadata/AboutOpenMetadata.tsx
- src/components/Achievement/Achievement.tsx
- src/components/FooterDev/FooterDev.tsx
- src/components/Header/Clients.tsx
- src/components/Header/Header.tsx
- src/components/IntegrationsDev/IntegrationsDev.tsx
- src/components/KeyDataAssets/KeyDataAssets.tsx
- src/components/NavbarDev/NavbarDev.component.tsx
- src/components/Service/Service.tsx
- src/components/Testimonials/Testimonials.tsx
- src/components/TryOpenMetadata/TryOpenMetadata.tsx
Add priority and lazy loading to images.
> Update image loading property

- src/components/Achievement/Achievement.tsx
- src/components/Header/Clients.tsx
- src/components/Header/Header.tsx
- src/components/NavbarDev/NavbarDev.component.tsx
- src/components/NavbarDev/NavbarStrip.component.tsx
- src/components/Service/Service.tsx
> Add loading eager to images

- src/components/TeamsSection/TeamsSection.tsx
- src/constants/Testimonials.constants.tsx
> support savii in team list

- src/components/AboutOpenMetadata/AboutOpenMetadata.tsx
- src/components/Achievement/Achievement.tsx
- src/components/FooterDev/FooterDev.tsx
- src/components/Header/Header.tsx
- src/components/IntegrationsDev/IntegrationsDev.tsx
- src/components/KeyDataAssets/KeyDataAssets.tsx
- src/components/NavbarDev/NavbarStrip.component.tsx
- src/components/Service/Service.tsx
- src/components/Testimonials/Testimonials.tsx
- src/components/TryOpenMetadata/TryOpenMetadata.tsx
Updated the font sizes as we have in figma.
> updated the font sizes as per figma

- src/components/AboutOpenMetadata/AboutOpenMetadata.tsx
- src/components/Achievement/Achievement.tsx
- src/components/FooterDev/FooterDev.tsx
- src/components/Header/Clients.tsx
- src/components/Header/Header.tsx
- src/components/IntegrationsDev/IntegrationsDev.tsx
- src/components/KeyDataAssets/KeyDataAssets.tsx
- src/components/NavbarDev/NavbarDev.component.tsx
- src/components/NavbarDev/NavbarStrip.component.tsx
- src/components/Service/Service.tsx
- src/components/Testimonials/Testimonials.tsx
- src/components/TryOpenMetadata/TryOpenMetadata.tsx
- src/constants/Testimonials.constants.tsx
Add letter spacing in all texts and update alignment and layouting.
> Add letter spacings and fix layouting

- public/assets/header/left-box-big.svg
- public/assets/header/right-box-big.svg
- src/components/Header/Header.tsx
- src/components/NavbarDev/NavbarDev.component.tsx
- src/components/Testimonials/Testimonials.tsx
- src/styles/globals.css
> Update header and testimonial boxes

- src/constants/Achievement.constants.tsx
> Update kpi data

- src/components/Testimonials/Testimonials.tsx
- src/constants/Testimonials.constants.tsx
Updated the logo sizes for testimonial section.
> Update logo sizes for testimonial

- src/components/FooterDev/FooterDev.tsx
> Update FooterDev.tsx - remove schemas link

- src/constants/Integrations.constants.tsx
Updated the URLs for ADLS, s3 and GCS data lake.
> Update datalake connector URLs.

- src/components/IntegrationsDev/IntegrationsDev.tsx
- src/constants/Integrations.constants.tsx
Updated the URL for the connectors which had broken links.
> Update connector url

- src/pages/resources/webinar/carrefour-brasil-spotlight/ty-video.tsx
> Update ty page header

- src/pages/community.tsx
https://deploy-preview-214--open-metadata.netlify.app/community
> Update community meets

- src/pages/community.tsx
- src/pages/index.tsx
- src/pages/resources/webinar/carrefour-brasil-spotlight/index.tsx
- src/pages/resources/webinar/carrefour-brasil-spotlight/ty-video.tsx
- src/pages/resources/webinar/data-culture/ty-video.tsx
- src/pages/resources/webinar/gorgias-spotlight/ty-video.tsx
> Stick footer to bottom

- content/product-updates/v1.4.0.md
- content/product-updates/v1.7.0.md
- src/pages/product-updates.tsx
> Update urls for youtube videos

- content/product-updates/v1.8.0.md
- content/product-updates/v1.8.1.md
- content/product-updates/versions.json
- src/components/FooterDev/FooterDev.tsx
> chore(ui): change logs for 1.8.1

- src/components/TryOpenMetadata/TryOpenMetadata.tsx
- src/constants/TryOpenMetadata.constants.tsx
- src/pages/product-updates.tsx
- Removed the New tag from the card.
- Updated the list styles in product updates page.
> minor: remove New from a card

- content/product-updates/v1.8.9.md
- content/product-updates/versions.json
> Add product updates for 1.8.9

- src/components/IntegrationsDev/IntegrationsDev.tsx
- src/constants/KeyDataAssets.constants.tsx
- src/constants/Service.constants.tsx
- src/pages/_app.tsx
- Updated the page title to ensure accuracy and consistency with branding.
- Modified the connector count to display the current number of available connectors. (80 -> 90)
> Update title and connector count

- content/product-updates/v1.9.5.md
- content/product-updates/versions.json
> Add Product Updates for v1.9.5

- content/product-updates/v1.9.7.md
- content/product-updates/versions.json
Added changelog for 1.9.7 release.
> chore(ui): changelog for 1.9.7
